[uwsgi]
# Who will run the code
uid = __APP__
gid = __APP__

# Number of workers
workers = 4

# The right granted on the created socket
chmod-socket = 666

# Plugin to use and interpretor config
single-interpreter = true
master = true
plugin = python3

# Application base folder
base = /opt/yunohost/radicale

# Virtualenv and python path
virtualenv = __INSTALL_DIR__/radicale
pythonpath = __INSTALL_DIR__/radicale
chdir= /var/www/__APP__
wsgi-file=/var/www/__APP__/radicale.wsgi
