#!/bin/bash

source /usr/share/yunohost/helpers

user=$1
install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)

sudo cp -a $install_dir/default_collections/USER $install_dir/collections/$user
sudo cp -a $install_dir/default_collections/USER.props $install_dir/collections/$user.props
