#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)
infcloud=$(ynh_app_setting_get $app infcloud)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

CHECK_SIZE "$final_path"
ynh_backup "$final_path"
CHECK_SIZE "/opt/yunohost/$app"
ynh_backup "/opt/yunohost/$app"

#=================================================
# BACKUP NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# BACKUP PHP-FPM CONFIGURATION
#=================================================

if [ $infcloud -eq 1 ]
then
	ynh_backup "/etc/php5/fpm/pool.d/$app.conf"
fi

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP UWSGI CONFIG
#=================================================

ynh_backup "/etc/uwsgi/apps-available/radicale.ini"

#=================================================
# BACKUP RADICALE CONFIGURATION
#=================================================

CHECK_SIZE "/etc/$app"
ynh_backup "/etc/$app"

#=================================================
# BACKUP LOGROTATE CONFIGURATION
#=================================================

ynh_backup "/etc/logrotate.d/$app"
