#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

# Exit on command errors and treat unset variables as an error
set -eu

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

if [ ! -e _common.sh ]; then
	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
	sudo cp ../settings/scripts/_common.sh ./_common.sh
	sudo chmod a+rx _common.sh
fi
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

# Récupère les infos de l'application.
app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)
infcloud=$(ynh_app_setting_get $app infcloud)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP OF THE MAIN DIR OF THE APP
#=================================================

CHECK_SIZE "$final_path"
ynh_backup "$final_path" "sources"
CHECK_SIZE "/opt/yunohost/$app"
ynh_backup "/opt/yunohost/$app" "virtualenv"

#=================================================
# BACKUP OF THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "nginx.conf"

#=================================================
# BACKUP OF THE PHP-FPM CONFIGURATION
#=================================================

if [ $infcloud -eq 1 ]
then
	ynh_backup "/etc/php5/fpm/pool.d/$app.conf" "php-fpm.conf"
	ynh_backup "/etc/php5/fpm/conf.d/20-$app.ini" "php-fpm.ini"
fi

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP OF THE UWSGI CONFIG
#=================================================

ynh_backup "/etc/uwsgi/apps-available/radicale.ini" "uwsgi_conf"

#=================================================
# BACKUP OF THE RADICALE CONFIGURATION
#=================================================

CHECK_SIZE "/etc/$app"
ynh_backup "/etc/$app" "etc"

#=================================================
# BACKUP OF THE LOGROTATE CONFIGURATION
#=================================================

ynh_backup "/etc/logrotate.d/$app" "logrotate"
