#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ACTIVATE MAINTENANCE MODE
#=================================================
ynh_script_progression "Activate maintenance mode"
path=$old_path
domain=$old_domain
ynh_maintenance_mode_ON

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# MODIFY CONFIG FILES
#=================================================
ynh_replace --match="^base_prefix = $old_path.*" --replace="base_prefix = ${new_path%/}/" --file="/etc/$app/config"

if [ $infcloud -eq 1 ]; then
	ynh_replace --match="href: 'https://$old_domain$old_path'," --replace="href: 'https://$new_domain${new_path%/}/'," --file="$install_dir/infcloud/config.js"
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=uwsgi --action="restart"

#=================================================
# DEACTIVE MAINTENANCE MODE
#=================================================
ynh_script_progression "Disable maintenance mode"
path=$old_path
domain=$old_domain
ynh_maintenance_mode_OFF

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
