#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

old_domain=$YNH_APP_OLD_DOMAIN
old_path=$YNH_APP_OLD_PATH

new_domain=$YNH_APP_NEW_DOMAIN
new_path=$YNH_APP_NEW_PATH

app=$YNH_APP_INSTANCE_NAME

#=================================================
# LOAD SETTINGS
#=================================================

infcloud=$(ynh_app_setting_get $app infcloud)
final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# CHECK THE SYNTAX OF THE PATHS
#=================================================

# Remove /infcloud in $old_path
if [ $infcloud -eq 1 ]
then
	old_path="${old_path%/infcloud}"
fi

test -n "$old_path" || old_path="/"
test -n "$new_path" || new_path="/"
new_path=$(ynh_normalize_url_path $new_path)
old_path=$(ynh_normalize_url_path $old_path)

#=================================================
# ACTIVATE MAINTENANCE MODE
#=================================================

path_url=$old_path
domain=$old_domain
ynh_maintenance_mode_ON

#=================================================
# CHECK WHICH PARTS SHOULD BE CHANGED
#=================================================

change_domain=0
if [ "$old_domain" != "$new_domain" ]
then
	change_domain=1
fi

change_path=0
if [ "$old_path" != "$new_path" ]
then
	change_path=1
fi

#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# MODIFY URL IN NGINX CONF
#=================================================

nginx_conf_path=/etc/nginx/conf.d/$old_domain.d/$app.conf

# Change the path in the nginx config file
if [ $change_path -eq 1 ]
then
	# Make a backup of the original nginx config file if modified
	ynh_backup_if_checksum_is_different "$nginx_conf_path"

	# Set global variables for nginx helper
	domain="$old_domain"
	path_url="$new_path"

	# Store path_url setting
	ynh_app_setting_set $app path_url "$path_url"

	# Create a dedicated nginx config
	ynh_add_nginx_config
fi

# Change the domain for nginx
if [ $change_domain -eq 1 ]
then
	# Delete file checksum for the old conf file location
	ynh_delete_file_checksum "$nginx_conf_path"
	mv $nginx_conf_path /etc/nginx/conf.d/$new_domain.d/$app.conf

	# Store file checksum for the new config file location
	ynh_store_file_checksum "/etc/nginx/conf.d/$new_domain.d/$app.conf"
fi

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# MODIFY CONFIG FILES
#=================================================

ynh_replace_string "^base_prefix = $old_path.*" "base_prefix = ${new_path%/}/" /etc/$app/config

if [ $infcloud -eq 1 ]; then
	ynh_replace_string "href: 'https://$old_domain$old_path'," "href: 'https://$new_domain${new_path%/}/'," "$final_path/infcloud/config.js"
fi

#=================================================
# UPDATE SSOWAT
#=================================================

if [ $infcloud -eq 1 ]
then
	# Add /infcloud to the path of radicale to access it from the portal
	echo "sudo yunohost --verbose app setting $app path -v \"${new_path%/}/infcloud\"; sudo yunohost app ssowatconf" | at now + 1 min >&2
	domain_regex=$(echo "$new_domain" | sed 's@-@.@g')
	# Radicale is always accessible (For access to ressources)
	ynh_app_setting_set $app skipped_regex "$domain_regex$new_path"
fi

#=================================================
# RESTART UWSGI
#=================================================

ynh_systemd_action --action=restart --service_name=uwsgi

#=================================================
# GENERIC FINALISATION
#=================================================
# RELOAD NGINX
#=================================================

ynh_systemd_action --action=reload --service_name=nginx

#=================================================
# DEACTIVE MAINTENANCE MODE
#=================================================

path_url=$old_path
domain=$old_domain
ynh_maintenance_mode_OFF
