#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing the systemd service..."

ynh_systemctl --action="stop" --service=uwsgi

# Delete uwsgi configuration
if [ -h "/etc/uwsgi/apps-enabled/$app.ini" ]; then
	echo "Delete uwsgi config"
	ynh_safe_rm "/etc/uwsgi/apps-enabled/$app.ini"
fi

ynh_safe_rm "/etc/uwsgi/apps-available/$app.ini"

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove the dedicated PHP-FPM config
ynh_config_remove_phpfpm

# Remove a directory securely
ynh_safe_rm "/etc/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
