#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Restoring the NGINX web server configuration..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

# mkdir -p /opt/yunohost
# ynh_restore "/opt/yunohost/$app"

# chown -R radicale: "/opt/yunohost/$app"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

if [ $infcloud -eq 1 ]
then
	ynh_restore "/etc/php/$php_version/fpm/pool.d/$app.conf"
fi

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

yunohost service add $app --log="/var/log/uwsgi/app/radicale.log"

#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_script_progression "Restoring $app's systemd service..."

ynh_restore "/etc/uwsgi/apps-available/radicale.ini"
ln -s /etc/uwsgi/apps-available/radicale.ini /etc/uwsgi/apps-enabled/

#=================================================
# RESTORE VARIOUS FILES
#=================================================
ynh_script_progression "Restoring various files..."

ynh_restore "/etc/$app/"

#=================================================
# RESTORE THE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Restoring the logrotate configuration..."

mkdir -p /var/log/$app
touch /var/log/$app/$app.log
chown $app -R /var/log/$app

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service=uwsgi --action=restart

if [ $infcloud -eq 1 ]
then
	ynh_systemctl --service=php$php_version-fpm --action=reload
fi

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
