#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Load settings" --weight=6

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
path_url=$(ynh_app_setting_get --app=$app --key=path)
admin=$(ynh_app_setting_get --app=$app --key=admin)
infcloud=$(ynh_app_setting_get --app=$app --key=infcloud)
language=$(ynh_app_setting_get --app=$app --key=language)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)
version=$(ynh_app_setting_get --app=$app --key=version)
overwrite_logging=$(ynh_app_setting_get --app=$app --key=overwrite_logging)
overwrite_config=$(ynh_app_setting_get --app=$app --key=overwrite_config)
overwrite_infcloud=$(ynh_app_setting_get --app=$app --key=overwrite_infcloud)
overwrite_nginx=$(ynh_app_setting_get --app=$app --key=overwrite_nginx)
overwrite_phpfpm=$(ynh_app_setting_get --app=$app --key=overwrite_phpfpm)

# Optional parameters from config-panel feature
firstdayofweek=$(ynh_app_setting_get --app=$app --key=firstdayofweek)
activeview=$(ynh_app_setting_get --app=$app --key=activeview)
openformmode=$(ynh_app_setting_get --app=$app --key=openformmode)
startofbusiness=$(ynh_app_setting_get --app=$app --key=startofbusiness)
endofbusiness=$(ynh_app_setting_get --app=$app --key=endofbusiness)
defaulteventduration=$(ynh_app_setting_get --app=$app --key=defaulteventduration)

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensure downward compatibility"

ynh_app_setting_delete $app unprotected_regex

if [ -d /usr/local/radicale ]
then
	mkdir -p /opt/yunohost
	mv /usr/local/radicale /opt/yunohost/
fi

if [ -z "$version" ]
then
	# Retrieve the version number in the manifest file.
	version=$(ynh_app_upstream_version)
	ynh_app_setting_set $app version "$version"
fi

# Fix infcloud as a boolean
if [ "$infcloud" = "Yes" ]; then
	ynh_app_setting_set $app infcloud 1
	infcloud=1
elif [ "$infcloud" = "No" ]; then
	ynh_app_setting_set $app infcloud 0
	infcloud=0
fi

# If overwrite_logging doesn't exist, create it
if [ -z "$overwrite_logging" ]; then
	overwrite_logging=1
	ynh_app_setting_set $app overwrite_logging $overwrite_logging
fi

# If overwrite_config doesn't exist, create it
if [ -z "$overwrite_config" ]; then
	overwrite_config=1
	ynh_app_setting_set $app overwrite_config $overwrite_config
fi

# If overwrite_infcloud doesn't exist, create it
if [ -z "$overwrite_infcloud" ]; then
	overwrite_infcloud=1
	ynh_app_setting_set $app overwrite_infcloud $overwrite_infcloud
fi

# If overwrite_nginx doesn't exist, create it
if [ -z "$overwrite_nginx" ]; then
	overwrite_nginx=1
	ynh_app_setting_set $app overwrite_nginx $overwrite_nginx
fi

# If overwrite_phpfpm doesn't exist, create it
if [ -z "$overwrite_phpfpm" ]; then
	overwrite_phpfpm=1
	ynh_app_setting_set $app overwrite_phpfpm $overwrite_phpfpm
fi

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================
ynh_script_progression --message="Backup the app before upgrading" --weight=9

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# restore it if the upgrade fails
	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# Migrate legacy permissions to new system
#=================================================
if ynh_legacy_permissions_exists
then
	ynh_legacy_permissions_delete_all

	ynh_app_setting_delete --app=$app --key=is_public
fi

#=================================================
# CHECK THE PATH
#=================================================

if [ $infcloud -eq 1 ]; then
	# Remove /infcloud to deal with the path only.
	path_url=$(echo $path_url | sed "s@/infcloud@@")
fi

#=================================================
# ACTIVATE MAINTENANCE MODE
#=================================================
ynh_script_progression --message="Activate maintenance mode"

ynh_maintenance_mode_ON

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression --message="Upgrade dependencies"

ynh_install_app_dependencies $pkg_dependencies

#=================================================
# NGINX CONFIGURATION
#=================================================

# Overwrite the NGINX configuration only if it's allowed
if [ $overwrite_nginx -eq 1 ]
then
	ynh_script_progression --message="Reconfigure nginx" --weight=2
	ynh_add_nginx_config
	if [ $infcloud -eq 1 ]
	then
		# Add InfCloud in NGINX config
		ynh_replace_string "#INFCLOUD#" "" /etc/nginx/conf.d/$domain.d/$app.conf
	fi
	ynh_store_file_checksum "/etc/nginx/conf.d/$domain.d/$app.conf"
fi

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression --message="Create a dedicated user"

# Create a dedicated user (if not existing)
ynh_system_user_create $app

if [ $infcloud -eq 1 ]
then
	#=================================================
	# PHP-FPM CONFIGURATION
	#=================================================

	# Overwrite the php-fpm configuration only if it's allowed
	if [ $overwrite_phpfpm -eq 1 ]
	then
		ynh_script_progression --message="Reconfigure PHP-FPM" --weight=2
		# Create a dedicated php-fpm config
		ynh_add_fpm_config
	fi
fi

#=================================================
# SPECIFIC UPGRADE
#=================================================
# UPGRADE RADICALE IN ITS VIRTUALENV
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrade Radicale in its virtualenv" --weight=6
	# Upgrade pip packages
	ynh_secure_remove /opt/yunohost/$app
	virtualenv /opt/yunohost/$app
	version=$(ynh_app_setting_get $app version $version)
	bash -c "source /opt/yunohost/radicale/bin/activate && pip install radicale==$version python-ldap"
fi

#=================================================
# COPY FILES INTO $FINAL_PATH
#=================================================
ynh_script_progression --message="Download, check and unpack source"

# Copy files to the right place
mkdir -p $final_path/collections
cp ../conf/radicale.wsgi $final_path
# Copy extra files
cp -a ../sources/extra_files_radicale/. "$final_path"
# regex.py file is patched to fix the awful commit e807c3d35bea9cfcfcacac83b1b17d748ea15a39 that stop the reading of "rights" file after the first match.
mv "$final_path/regex.py" /opt/yunohost/$app/lib/python*/site-packages/radicale/rights/regex.py
if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	if [ "$infcloud" = "1" ]
	then
		#Instal InfCloud
		# Backup the content of $final_path
		final_path_backup=$final_path
		# Modify final_path for InfCloud installation
		final_path=$final_path/infcloud
		# If overwrite_infcloud is 0, copy the config file, then restore it.
		if [ $overwrite_infcloud -eq 0 ]; then
			cp -a $final_path/config.js ./config.js
		fi
		# Download and uncompress the source into final_path
		ynh_setup_source "$final_path"
		if [ $overwrite_infcloud -eq 0 ]; then
			mv ./config.js $final_path/config.js
		fi
		# Restore the content of $final_path
		final_path=$final_path_backup
	fi
fi

#=================================================
# CONFIGURE RADICALE
#=================================================
ynh_script_progression --message="Reconfigure Radicale" --weight=5

# Overwrite the logging config file only if it's allowed
if [ $overwrite_logging -eq 1 ]
then
	# Verify the checksum of a file, stored by `ynh_store_file_checksum` in the install script.
	ynh_backup_if_checksum_is_different "/etc/$app/logging"
	cp ../conf/logging /etc/$app/
	# Recalculate and store the checksum of the file for the next upgrade.
	ynh_store_file_checksum "/etc/$app/logging"
fi

# Overwrite the config file only if it's allowed
if [ $overwrite_config -eq 1 ]
then
	# Verify the checksum of a file, stored by `ynh_store_file_checksum` in the install script.
	ynh_backup_if_checksum_is_different "/etc/$app/config"
	cp ../conf/config /etc/$app/
	ynh_replace_string "__PATH__" "${path_url%/}" /etc/$app/config
	ynh_replace_string "__FINALPATH__" "$final_path" /etc/$app/config
	# Recalculate and store the checksum of the file for the next upgrade.
	ynh_store_file_checksum "/etc/$app/config"
fi

# Overwrite the InfCloud config file only if it's allowed
if [ $overwrite_infcloud -eq 1 ]
then
	if [ $infcloud -eq 1 ]
	then
		# InfCloud configuration
		# Set language
		case "$language" in
			"Czech") language="cs_CZ"
			;;
			"Danish") language="da_DK"
			;;
			"German") language="de_DE"
			;;
			"English/US") language="en_US"
			;;
			"Spanish") language="es_ES"
			;;
			"French") language="fr_FR"
			;;
			"Italian") language="it_IT"
			;;
			"Japan") language="ja_JP"
			;;
			"Hungarian") language="hu_HU"
			;;
			"Dutch") language="nl_NL"
			;;
			"Slovak") language="sk_SK"
			;;
			"Turkish") language="tr_TR"
			;;
			"Russian") language="ru_RU"
			;;
			"Ukrainian") language="uk_UA"
			;;
			"Chinese") language="zh_CN"
			;;
		esac
		ynh_app_setting_set $app language $language
		# Verify the checksum of a file, stored by `ynh_store_file_checksum` in the install script.
		ynh_backup_if_checksum_is_different "$final_path/infcloud/config.js"
		cp ../conf/config.js "$final_path/infcloud/"
		ynh_replace_string "__DOMAIN__" "$domain" "$final_path/infcloud/config.js"
		ynh_replace_string "__PATH__" "${path_url%/}" "$final_path/infcloud/config.js"
		ynh_replace_string "__LANG__" "$language" "$final_path/infcloud/config.js"
		ynh_replace_string "__ADMIN__" "$admin" "$final_path/infcloud/config.js"
		ynh_replace_string "__TIMEZONE__" "$(cat /etc/timezone)" "$final_path/infcloud/config.js"

		# Optional parameters from config-panel feature
		if [ -n "$firstdayofweek" ]; then
			ynh_replace_string "\(^var globalDatepickerFirstDayOfWeek=\).*" "\1$firstdayofweek;" "$final_path/infcloud/config.js"
		fi
		if [ -n "$activeview" ]; then
			ynh_replace_string "\(^var globalActiveView=\).*" "\1\'$activeview\';" "$final_path/infcloud/config.js"
		fi
		if [ -n "$openformmode" ]; then
			ynh_replace_string "\(^var globalOpenFormMode=\).*" "\1\'$openformmode\';" "$final_path/infcloud/config.js"
		fi
		if [ -n "$startofbusiness" ]; then
			ynh_replace_string "\(^var globalCalendarStartOfBusiness=\).*" "\1$startofbusiness;" "$final_path/infcloud/config.js"
		fi
		if [ -n "$endofbusiness" ]; then
			ynh_replace_string "\(^var globalCalendarEndOfBusiness=\).*" "\1$endofbusiness;" "$final_path/infcloud/config.js"
		fi
		if [ -n "$defaulteventduration" ]; then
			ynh_replace_string "\(^var globalDefaultEventDuration=\).*" "\1$defaulteventduration;" "$final_path/infcloud/config.js"
		fi
		# Recalculate and store the checksum of the file for the next upgrade.
		ynh_store_file_checksum "$final_path/infcloud/config.js"
	fi
fi

#=================================================
# SET PERMISSIONS ON RADICALE DIRECTORIES
#=================================================

chown radicale: -R /opt/yunohost/$app

# Fix permission
chmod 755 /etc/$app/
find /opt/yunohost/$app/ -type d -exec chmod 2755 {} \;
find /opt/yunohost/$app/ -type f -exec chmod g+r,o+r {} \;
chmod 644 /etc/$app/*
chown -R radicale: $final_path
mkdir -p /var/log/$app
touch /var/log/$app/$app.log
chown radicale -R /var/log/$app
# Set default permissions as radicale do.
chmod 666 -R $final_path/default_collections
chmod 777 $final_path/default_collections $final_path/default_collections/USER

#=================================================
# CONFIGURE UWSGI FOR RADICALE
#=================================================

cp ../conf/radicale.ini /etc/uwsgi/apps-available/

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================
ynh_script_progression --message="Restart Radicale" --weight=2

ynh_systemd_action --action=restart --service_name=uwsgi
yunohost service add uwsgi --log="/var/log/uwsgi/app/radicale.log"

#=================================================
# PREPARE THE HOOKS
#=================================================

# Modify the hooks for create user collections and to remove them.
ynh_replace_string "__FINALPATH__" "$final_path" ../hooks/post_user_create
ynh_replace_string "__FINALPATH__" "$final_path" ../hooks/post_user_delete

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Reconfigure logrotate" --weight=3

ynh_use_logrotate --non-append

#=================================================
# GENERIC FINALISATION
#=================================================
# SETUP SSOWAT
#=================================================
ynh_script_progression --message="Reconfigure SSOwat" --weight=2

if [ $infcloud -eq 1 ]
then
	# Add /infcloud to the path of radicale to access it from the portal
	# Replace radicale by InfCloud into YunoHost portal
	ynh_app_setting_set $app path ${path_url%/}/infcloud
	# Protect InfCloud access
	ynh_app_setting_set $app protected_uris "/"
	domain_regex=$(echo "$domain" | sed 's@-@.@g')
	# Radicale is always accessible (For access to ressources)
	ynh_app_setting_set $app skipped_regex "$domain_regex$path_url"
else
	# If only radicale is installed
	# Radicale is always accessible (For access to ressources)
	ynh_app_setting_set $app unprotected_uris "/"
fi

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reload NGINX"

ynh_systemd_action --action=reload --service_name=nginx

#=================================================
# DEACTIVE MAINTENANCE MODE
#=================================================
ynh_script_progression --message="Disable maintenance mode" --weight=5

ynh_maintenance_mode_OFF

#=================================================
# SEND A README FOR THE ADMIN
#=================================================

# Get main domain and buid the url of the admin panel of the app.
admin_panel="https://$(grep portal_domain /etc/ssowat/conf.json | cut -d'"' -f4)/yunohost/admin/#/apps/$app"

# Build the changelog
ynh_app_changelog || true

if [ $infcloud -eq 1 ]
then
	infcloud_config="
InfCloud has its own config file, at $final_path/infcloud/config.js
"
else
	infcloud_config=""
fi

echo "Use the file /etc/radicale/config to change the main configuration of radicale.
The file /etc/radicale/logging to change the level of logging.
And the file /etc/radicale/rights to edit the way the calendars will be shared.
$infcloud_config
You can configure this app easily by using the experimental __URL_TAG1__config-panel feature__URL_TAG2__$admin_panel/config-panel__URL_TAG3__.
You can also find some specific actions for this app by using the experimental __URL_TAG1__action feature__URL_TAG2__$admin_panel/actions__URL_TAG3__.

If you're facing an issue or want to improve this app, please open a new issue in this __URL_TAG1__project__URL_TAG2__https://github.com/YunoHost-Apps/radicale_ynh__URL_TAG3__.

---

Changelog since your last upgrade:
$(cat changelog)" > mail_to_send

ynh_send_readme_to_admin --app_message="mail_to_send" --recipients="$admin" --type="upgrade"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade completed" --last
