#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path)
admin=$(ynh_app_setting_get $app admin)
infcloud=$(ynh_app_setting_get $app infcloud)
language=$(ynh_app_setting_get $app language)
final_path=$(ynh_app_setting_get $app final_path)
version=$(ynh_app_setting_get $app version)

#=================================================
# FIX OLD THINGS
#=================================================

ynh_app_setting_delete $app unprotected_regex

if [ -d /usr/local/radicale ]
then
	sudo mkdir -p /opt/yunohost
	sudo mv /usr/local/radicale /opt/yunohost/
fi

if [ -z "$version" ]
then
	version=$(grep '\"version\": ' ../manifest.json | cut -d '"' -f 4)	# Retrieve the version number in the manifest file.
	ynh_app_setting_set $app version "$version"
fi

if [ "$infcloud" = "Yes" ]; then
	ynh_app_setting_set $app infcloud 1	# Fixe infcloud en booléen
	infcloud=1
elif [ "$infcloud" = "No" ]; then
	ynh_app_setting_set $app infcloud 0
	infcloud=0
fi

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================

BACKUP_BEFORE_UPGRADE	# Backup the current version of the app
ynh_clean_setup () {
	BACKUP_FAIL_UPGRADE	# restore it if the upgrade fails
}
ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.

#=================================================
# CHECK THE PATH
#=================================================


if [ $infcloud -eq 1 ]; then
	path_url=$(echo $path_url | sed "s@/infcloud@@")	# Retire /infcloud pour traiter le path seul.
fi
path_url=$(ynh_normalize_url_path $path_url)	# Vérifie et corrige la syntaxe du path.

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# NGINX CONFIGURATION
#=================================================

ynh_nginx_config
if [ "$path_url" = "/" ]
then
	ynh_replace_string "__PATH_NO_ROOT__" "" /etc/nginx/conf.d/$domain.d/$app.conf
else
	ynh_replace_string "__PATH_NO_ROOT__" "$path_url" /etc/nginx/conf.d/$domain.d/$app.conf
fi
if [ $infcloud -eq 1 ]
then	# Ajoute InfCloud dans la config Nginx
	ynh_replace_string "#INFCLOUD#" "" /etc/nginx/conf.d/$domain.d/$app.conf
fi
ynh_store_file_checksum "$finalnginxconf"

#=================================================
# CREATE DEDICATED USER
#=================================================

ynh_system_user_create $app	# Create the dedicated user, if not exist

if [ $infcloud -eq 1 ]
then
	#=================================================
	# PHP-FPM CONFIGURATION
	#=================================================

	ynh_fpm_config	# Créer le fichier de configuration du pool php-fpm et le configure.
fi

#=================================================
# SPECIFIC UPGRADE
#=================================================
# UPGRADE RADICALE IN ITS VIRTUALENV
#=================================================

# Upgrade pip packages
ynh_secure_remove /opt/yunohost/$app
sudo virtualenv /opt/yunohost/$app
sudo bash -c "source /opt/yunohost/radicale/bin/activate && pip install radicale==$version python-ldap"

#=================================================
# COPY FILES INTO $FINAL_PATH
#=================================================

# Copy files to the right place
sudo mkdir -p $final_path/collections
sudo cp ../conf/radicale.wsgi $final_path
# Copie les fichiers additionnels ou modifiés.
sudo cp -a ../sources/extra_files_radicale/. "$final_path"
# Le fichier regex.py est patché pour corrigé le commit destructeur e807c3d35bea9cfcfcacac83b1b17d748ea15a39 du 3/12/2015 qui arrête la lecture du fichier rights à la première occurence validée.
sudo mv "$final_path/regex.py" /opt/yunohost/$app/lib/python*/site-packages/radicale/rights/regex.py
ynh_secure_remove /opt/yunohost/$app/lib/python*/site-packages/radicale/rights/regex.pyc
if [ "$infcloud" = "1" ]
then	#Instal InfCloud
	final_path_backup=$final_path	# Sauvegarde le contenu de $final_path
	final_path=$final_path/infcloud	# Change final_path pour l'installation de infcloud
	ynh_setup_source "$final_path"	# Télécharge la source, décompresse et copie dans $final_path
	final_path=$final_path_backup	# Restaure le contenu de $final_path
fi

#=================================================
# CONFIGURE RADICALE
#=================================================

ynh_backup_if_checksum_is_different "/etc/$app/config"	# Créé un backup du fichier de config si il a été modifié.
sudo cp ../conf/config /etc/$app/
ynh_backup_if_checksum_is_different "/etc/$app/logging"	# Créé un backup du fichier de config si il a été modifié.
sudo cp ../conf/logging /etc/$app/
ynh_store_file_checksum "/etc/$app/logging"	# Réenregistre la somme de contrôle du fichier de config
ynh_replace_string "__PATH__" "$path_url" /etc/$app/config
ynh_replace_string "__FINALPATH__" "$final_path" /etc/$app/config
ynh_store_file_checksum "/etc/$app/config"	# Réenregistre la somme de contrôle du fichier de config
if [ $infcloud -eq 1 ]
then	#Configuration InfCloud
	# Détermine la langue
	case "$language" in
		"Czech") language="cs_CZ"
		;;
		"Danish") language="da_DK"
		;;
		"German") language="de_DE"
		;;
		"English/US") language="en_US"
		;;
		"Spanish") language="es_ES"
		;;
		"French") language="fr_FR"
		;;
		"Italian") language="it_IT"
		;;
		"Japan") language="ja_JP"
		;;
		"Hungarian") language="hu_HU"
		;;
		"Dutch") language="nl_NL"
		;;
		"Slovak") language="sk_SK"
		;;
		"Turkish") language="tr_TR"
		;;
		"Russian") language="ru_RU"
		;;
		"Ukrainian") language="uk_UA"
		;;
		"Chinese") language="zh_CN"
		;;
	esac
	ynh_app_setting_set $app language $language
	ynh_backup_if_checksum_is_different "$final_path/infcloud/config.js"	# Créé un backup du fichier de config si il a été modifié.
	sudo cp ../conf/config.js "$final_path/infcloud/"
	ynh_replace_string "__DOMAIN__" "$domain" "$final_path/infcloud/config.js"
	ynh_replace_string "__PATH__" "$path_url" "$final_path/infcloud/config.js"
	ynh_replace_string "__LANG__" "$language" "$final_path/infcloud/config.js"
	ynh_replace_string "__ADMIN__" "$admin" "$final_path/infcloud/config.js"
	ynh_replace_string "__TIMEZONE__" "$(cat /etc/timezone)" "$final_path/infcloud/config.js"
	ynh_store_file_checksum "$final_path/infcloud/config.js"	# Réenregistre la somme de contrôle du fichier de config
fi

#=================================================
# SET PERMISSIONS ON RADICALE'S DIRECTORIES
#=================================================

sudo chown radicale: -R /opt/yunohost/$app

# Fix permission
sudo chmod 755 /etc/$app/
sudo find /opt/yunohost/$app/ -type d -exec chmod 2755 {} \;
sudo find /opt/yunohost/$app/ -type f -exec chmod g+r,o+r {} \;
sudo chmod 644 /etc/$app/*
sudo chown -R radicale: $final_path
sudo mkdir -p /var/log/$app
sudo touch /var/log/$app/$app.log
sudo chown radicale -R /var/log/$app
# Droit par défaut des dossiers de collections utilisateurs, tels qu'ils sont créés par radicale.
sudo chmod 666 -R $final_path/default_collections
sudo chmod 777 $final_path/default_collections $final_path/default_collections/USER

#=================================================
# CONFIGURE UWSGI FOR RADICALE
#=================================================

sudo cp ../conf/radicale.ini /etc/uwsgi/apps-available/

#=================================================
# RESTART UWSGI
#=================================================

sudo systemctl restart uwsgi

#=================================================
# PREPARE THE HOOKS
#=================================================

# Modification des hook pour la création des collections par défaut des nouveaux utilisateurs. Et leur suppression
ynh_replace_string "__FINALPATH__" "$final_path" ../hooks/post_user_create
ynh_replace_string "__FINALPATH__" "$final_path" ../hooks/post_user_delete

#=================================================
# GENERIC FINALISATION
#=================================================
# SETUP SSOWAT
#=================================================

if [ $infcloud -eq 1 ]
then	# /infcloud vient se rajouter à l'adresse de radicale pour y être associé sur le portail.
	ynh_app_setting_set $app path $path_url/infcloud	# Remplace radicale par InfCloud dans le portail Yunohost
	ynh_app_setting_set $app protected_uris "/"	# Protège l'accès à infcloud
	domain_regex=$(echo "$domain" | sed 's@-@.@g')
	ynh_app_setting_set $app skipped_regex "$domain_regex$path_url"	# Radicale est accessible librement (pour l'accès distant aux ressources)
else	# Si seul radicale est installé.
	ynh_app_setting_set $app unprotected_uris "/"	# Radicale est accessible librement (pour l'accès distant aux ressources)
fi

#=================================================
# RELOAD NGINX
#=================================================

sudo systemctl reload nginx
